---
# In Reddit, each participant is a Reddit author

# *Default configuration to simplify experiment setup
defaults:
  - base # Inherit from base config
  - _self_ # This ensures your config overrides the base config
  - atk_config: cifar10_multishot

# *Aggregator
aggregator: unweighted_fedavg

# *Specify if the attack is enabled
no_attack: False

# *Simulation configuration
num_rounds: 600
num_clients: 83293 # Each user is a client
num_clients_per_round: 100
federated_evaluation: False # Whether to perform federated evaluation (evaluate global model on client's validation set)
federated_val_split: 0.0 # Validation split for each client's dataset (should be > 0 if federated evaluation is True)

# *Dataset distribution configuration
dataset: Reddit # CIFAR10, CIFAR100, TinyImageNet, MNIST
task: next-word-prediction
sequence_length: 100 # Sequence-length
normalize: False # Normalize the dataset

# *Model configuration
model: lstm
num_classes: 50000 # Size of vocab

# *Test configuration
test_batch_size: 10
num_workers: 4 # Number of workers for dataloader
pin_memory: False
test_every: 1 # Test every x rounds

# *Default local training configuration (passed to clients during training)
client_config:
  # Training configuration
  task: ${task}
  sequence_length: ${sequence_length}
  local_epochs: 2
  batch_size: 20
  optimizer: sgd # Choose from the key in optimizer section below. Will be overridden to store DictConfig in client_optimizer_config
  momentum: 0
  weight_decay: 0
  lr: 20
